# Библиотека torch

Установка
```bash
pip install torch
```

## Математика

In [1]:
import numpy as np
import torch

In [2]:
x = torch.Tensor([1, 3, 5, 2, 1.3])
print(x)
x = torch.linspace(-np.pi, np.pi, 20, dtype=torch.float32)
print(x)
x = torch.arange(0, 10, 0.5, dtype=torch.float32)
print(x)
x = torch.ones(2, 1, 3, dtype=torch.float32)
print(x)

tensor([1.0000, 3.0000, 5.0000, 2.0000, 1.3000])
tensor([-3.1416, -2.8109, -2.4802, -2.1495, -1.8188, -1.4881, -1.1574, -0.8267,
        -0.4960, -0.1653,  0.1653,  0.4960,  0.8267,  1.1574,  1.4881,  1.8188,
         2.1495,  2.4802,  2.8109,  3.1416])
tensor([0.0000, 0.5000, 1.0000, 1.5000, 2.0000, 2.5000, 3.0000, 3.5000, 4.0000,
        4.5000, 5.0000, 5.5000, 6.0000, 6.5000, 7.0000, 7.5000, 8.0000, 8.5000,
        9.0000, 9.5000])
tensor([[[1., 1., 1.]],

        [[1., 1., 1.]]])


In [3]:
torch.manual_seed(42)
a = torch.randn((3, 2))
b = torch.randn((3, 2))
c = torch.randn((2, 4))
print(a)
print(b)
print(c)

tensor([[ 0.3367,  0.1288],
        [ 0.2345,  0.2303],
        [-1.1229, -0.1863]])
tensor([[ 2.2082, -0.6380],
        [ 0.4617,  0.2674],
        [ 0.5349,  0.8094]])
tensor([[ 1.1103, -1.6898, -0.9890,  0.9580],
        [ 1.3221,  0.8172, -0.7658, -0.7506]])


In [4]:
print(a + b ** 2)
print(torch.sin(a))
print(torch.cos(c))
print((a * 10).int())

tensor([[ 5.2128,  0.5358],
        [ 0.4476,  0.3018],
        [-0.8367,  0.4687]])
tensor([[ 0.3304,  0.1285],
        [ 0.2323,  0.2283],
        [-0.9013, -0.1853]])
tensor([[ 0.4444, -0.1187,  0.5496,  0.5752],
        [ 0.2461,  0.6843,  0.7208,  0.7313]])
tensor([[  3,   1],
        [  2,   2],
        [-11,  -1]], dtype=torch.int32)


#### Основное оличие от numpy

In [5]:
# До выполнения операций градиенты не заданы
a = torch.rand(2, 3, dtype=torch.float32, requires_grad=True)
x = torch.rand(2, 3, dtype=torch.float32, requires_grad=False)
y = torch.rand(2, 3, dtype=torch.float32, requires_grad=False)
print(a.grad, x.grad, y.grad)
print(a)
print(x)

None None None
tensor([[0.6343, 0.3644, 0.7104],
        [0.9464, 0.7890, 0.2814]], requires_grad=True)
tensor([[0.7886, 0.5895, 0.7539],
        [0.1952, 0.0050, 0.3068]])


In [6]:
y_pred = a ** 2 + x ** 3
loss = (y_pred - y).pow(2).sum()
loss.backward()
print(a.grad, x.grad, y.grad)

tensor([[ 1.9700, -0.8347,  0.8219],
        [ 0.7421, -0.1122, -0.4314]]) None None


# Вычисления на GPU

<img src="https://pytorch.org/assets/images/cudagraphs-pytorch.png" alt="CUDA" width=30% height=30%>


<img src="https://habrastorage.org/r/w1560/getpro/habr/post_images/5e2/048/3f5/5e20483f59e87b0a395b0fae0e6495c5.png" alt="CUDAplot" width=80% height=80%>

**FLOPS** (FLoating-point Operations Per Second) — внесистемная единица, используемая для измерения производительности компьютеров, показывающая, сколько операций с плавающей запятой в секунду выполняет данная вычислительная система.

## Архитектура CPU
<img src="https://habrastorage.org/r/w1560/getpro/habr/post_images/df0/8c2/4c3/df08c24c3fe92cd97356670729c318cd.png" alt="CUDAplot" width=40% height=40%>
ALU (Арифметико-логическое устройство) — блок процессора, который под управлением устройства управления служит для выполнения арифметических и логических преобразований (начиная от элементарных) над данными

## Архитектура GPU
<img src="https://habrastorage.org/r/w1560/getpro/habr/post_images/0fe/138/0cc/0fe1380ccbb321b289d16e39a499009a.png" alt="CUDAplot" width=40% height=40%>

Архитектура ядра GPU и логических элементов существенно проще, чем на CPU, а именно, отсутствуют Momory pre-fetcher, Branch predictor и прочие вспомогательные блоки.

In [7]:
# Определение, доступна ли CUDA
torch.cuda.is_available()

False

```python
x = torch.Tensor([1, 3, 5, 2, 1.3], device='cpu')
x = torch.Tensor([1, 3, 5, 2, 1.3], device='cuda:0')
```
или
```python
device = torch.device('cuda:0')
x = torch.Tensor([1, 3, 5, 2, 1.3], device=device)
```

# Нейронные сети

In [8]:
import torch.nn as nn

# Родительский класс для всех моделей и их элементов
nn.Module

method_list = [method for method in dir(nn.Module) if not method.startswith('_') and callable(getattr(nn.Module, method))]
print("Список методов:\n", method_list)

Список методов:
 ['add_module', 'apply', 'bfloat16', 'buffers', 'children', 'cpu', 'cuda', 'double', 'eval', 'extra_repr', 'float', 'forward', 'half', 'load_state_dict', 'modules', 'named_buffers', 'named_children', 'named_modules', 'named_parameters', 'parameters', 'register_backward_hook', 'register_buffer', 'register_forward_hook', 'register_forward_pre_hook', 'register_parameter', 'requires_grad_', 'share_memory', 'state_dict', 'to', 'train', 'type', 'zero_grad']


In [9]:
# Простая модель
class SimpleModel(nn.Module):
    def __init__(self, in_ch, out_ch):
        """Регистрация блоков"""
        super().__init__()
        self.fc1 = nn.Linear(in_ch, 32)  # Полносвязный слой 1
        self.fc2 = nn.Linear(32, out_ch, bias=False)  # Полносвязный слой 2
        self.relu = nn.ReLU()  # Функция активации
        
    def forward(self, x):
        """Прямой проход"""
        h = self.fc1(x)
        h = self.relu(h)
        h = self.fc2(h)
        y = self.relu(h)
        return y

In [10]:
model = SimpleModel(64, 10)

print('Model:', model)
print('FC1:', model.fc1)
print()
print('Weight:', model.fc1.weight.shape, '\n', model.fc1.weight)
print()
print('Weight:', model.fc1.bias.shape, '\n', model.fc1.bias)

Model: SimpleModel(
  (fc1): Linear(in_features=64, out_features=32, bias=True)
  (fc2): Linear(in_features=32, out_features=10, bias=False)
  (relu): ReLU()
)
FC1: Linear(in_features=64, out_features=32, bias=True)

Weight: torch.Size([32, 64]) 
 Parameter containing:
tensor([[ 0.0978, -0.0888,  0.0079,  ..., -0.0748,  0.0003, -0.0465],
        [-0.0087, -0.0847, -0.0858,  ..., -0.0445,  0.0652,  0.0657],
        [ 0.0467, -0.0220, -0.0331,  ...,  0.0415, -0.0371,  0.0772],
        ...,
        [-0.1192,  0.0228,  0.0171,  ...,  0.0446, -0.1053, -0.0153],
        [ 0.0475,  0.1020,  0.0376,  ...,  0.0884,  0.0099, -0.0895],
        [-0.0947, -0.0487,  0.0364,  ..., -0.0513, -0.0247,  0.0608]],
       requires_grad=True)

Weight: torch.Size([32]) 
 Parameter containing:
tensor([-0.0029,  0.1069, -0.0072, -0.0179,  0.0706, -0.0032, -0.0249,  0.0418,
         0.0986,  0.0312,  0.0870,  0.0810,  0.0353,  0.0435,  0.0403,  0.0130,
         0.1063,  0.1154,  0.0445, -0.0062,  0.1121, -0.097

In [11]:
list(model.parameters())

[Parameter containing:
 tensor([[ 0.0978, -0.0888,  0.0079,  ..., -0.0748,  0.0003, -0.0465],
         [-0.0087, -0.0847, -0.0858,  ..., -0.0445,  0.0652,  0.0657],
         [ 0.0467, -0.0220, -0.0331,  ...,  0.0415, -0.0371,  0.0772],
         ...,
         [-0.1192,  0.0228,  0.0171,  ...,  0.0446, -0.1053, -0.0153],
         [ 0.0475,  0.1020,  0.0376,  ...,  0.0884,  0.0099, -0.0895],
         [-0.0947, -0.0487,  0.0364,  ..., -0.0513, -0.0247,  0.0608]],
        requires_grad=True),
 Parameter containing:
 tensor([-0.0029,  0.1069, -0.0072, -0.0179,  0.0706, -0.0032, -0.0249,  0.0418,
          0.0986,  0.0312,  0.0870,  0.0810,  0.0353,  0.0435,  0.0403,  0.0130,
          0.1063,  0.1154,  0.0445, -0.0062,  0.1121, -0.0973,  0.0918,  0.0662,
          0.0803, -0.0096, -0.0933,  0.0892, -0.0547,  0.0329,  0.0708, -0.1168],
        requires_grad=True),
 Parameter containing:
 tensor([[ 0.0117, -0.0628,  0.1255, -0.1126,  0.1073,  0.1102,  0.0975,  0.1697,
           0.0268, -0.160

### Проход модели

In [12]:
x = torch.rand(4, 64)  # batch size = 4
y = torch.rand(4, 10)

w1_1 = model.fc1.weight.data.clone()  # Сохранение состояния весов

y_pred = model(x)  # Прямой проход
y_pred

tensor([[0.0447, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0899],
        [0.1487, 0.0000, 0.0328, 0.0000, 0.0000, 0.0000, 0.0132, 0.0000, 0.0000,
         0.0056],
        [0.1124, 0.0000, 0.1217, 0.0000, 0.0000, 0.0000, 0.0245, 0.0000, 0.0260,
         0.0228],
        [0.1245, 0.0000, 0.0407, 0.0000, 0.0000, 0.0000, 0.0208, 0.0000, 0.0000,
         0.0340]], grad_fn=<ReluBackward0>)

In [13]:
# Функция потерь L1 (MAE)
l1_loss = nn.L1Loss()
loss = l1_loss(y, y_pred)
print('Loss:', loss)

print('Grad before:', model.fc1.weight.grad)
loss.backward()  # Обратный проход
print('Grad after:', model.fc1.weight.grad)

Loss: tensor(0.6101, grad_fn=<L1LossBackward>)
Grad before: None
Grad after: tensor([[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [ 0.0058,  0.0047,  0.0101,  ...,  0.0026,  0.0090,  0.0050],
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        ...,
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [-0.0046, -0.0006, -0.0052,  ..., -0.0026, -0.0051, -0.0006]])


In [14]:
w1_2 = model.fc1.weight.data.clone()
print(w1_2 - w1_1)  # Веса не изменились

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])


### Обновление весов 

Для обновления весов в модели используются оптимизаторы:  
  
* SGD (Stochastic Gradient Descent) для оптимизации импульса.
* RMSprop – адаптивная оптимизация скорости обучения по методу Джеффа Хинтона.
* Adam – адаптивная оценка моментов, которая также использует адаптивную скорость обучения.

In [15]:
# Создание оптимизатора
opt = torch.optim.SGD(model.parameters(), lr=0.001)

In [16]:
opt.step()

In [17]:
w1_3 = model.fc1.weight.data.clone()
print(w1_3 - w1_2)  # Веса обновились

tensor([[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [-5.8291e-06, -4.6641e-06, -1.0058e-05,  ..., -2.6152e-06,
         -8.9854e-06, -4.9695e-06],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        ...,
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 4.6343e-06,  6.4820e-07,  5.2191e-06,  ...,  2.5630e-06,
          5.0627e-06,  6.2957e-07]])


In [18]:
# Градиенты всё ещё содержат старые значения, потому при следующем вычислении они будут учитываться
model.fc1.weight.grad

tensor([[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [ 0.0058,  0.0047,  0.0101,  ...,  0.0026,  0.0090,  0.0050],
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        ...,
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [-0.0046, -0.0006, -0.0052,  ..., -0.0026, -0.0051, -0.0006]])

In [19]:
# Чтобы обнулить градиенты, используем метод zero_grad() у оптимизатора
opt.zero_grad()
model.fc1.weight.grad

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])

### Batch
Batch (пакет) – количество обучающих примеров за одну итерацию. Чем больше batch size, тем больше места будет необходимо. Если batch size маленький, то изменение весов будет подстраиваться под отдельные примеры, а не под общие тенденции.

# Создание датасета

In [20]:
import torch.utils.data as data

In [21]:
class GeneratorDataset(data.Dataset):
    def __init__(self, in_size, out_size, num_samples, func='sin'):
        super().__init__()
        self.num_samples = num_samples
        self.in_size = in_size
        self.out_size = out_size
        self.func = func
        
    def __getitem__(self, index):
        x = torch.rand(self.in_size)
        if self.func == 'sin':
            x = torch.sin(x)
        elif self.func == 'cos':
            x = torch.cos(x)
        y = x[:self.out_size].clone()
        return x, y
    
    def __len__(self):
        return self.num_samples

In [22]:
dataset = GeneratorDataset(64, 10, 128)
dataloader = data.DataLoader(dataset, batch_size=16)
for x, y in dataloader:
    break
print(x.shape, y.shape)

torch.Size([16, 64]) torch.Size([16, 10])


### Обучение модели

In [23]:
model = SimpleModel(64, 10)
l1_loss = nn.L1Loss()
opt = torch.optim.Adam(model.parameters(), lr=0.001)

In [24]:
for x, y in dataloader:
    opt.zero_grad()
    
    y_pred = model(x)
    loss = l1_loss(y, y_pred)
    loss.backward()
    print('Loss', loss.item())
    opt.step()

Loss 0.44412118196487427
Loss 0.39865168929100037
Loss 0.4141206741333008
Loss 0.3751830458641052
Loss 0.39952030777931213
Loss 0.3894100785255432
Loss 0.35259371995925903
Loss 0.37724384665489197


# Пример модели UNet
  
[Репозиторий](https://github.com/milesial/Pytorch-UNet)  

<img src="https://camo.githubusercontent.com/41ded1456b9dbe13b8d73d8da539dac95cb8aa721ebe5fb798af732ca9f04c92/68747470733a2f2f692e696d6775722e636f6d2f6a6544567071462e706e67" alt="UNet" width=80% height=80%>
